### ISSUE TITLE
ValueError: A 2-dimensional array must be passed

### ISSUE THREAD

**Issue by albertiniufu** [maciejczyzewski/neural-chessboard#4]
I have tried both master and draft branches. 
When using mode "detect" they return the following message:

Traceback (most recent call last):
  File "main.py", line 108, in <module>
    modes[mode](args); print(utils.clock(), "done")
  File "main.py", line 63, in detect
    NC_LAYER += 1; layer()
  File "main.py", line 33, in layer
    points = LAPS(NC_IMAGE['main'], lines)
  File "/home/marcelo/neural-chessboard/neural-chessboard/laps.py", line 117, in LAPS
    points = laps_cluster(points)
  File "/home/marcelo/neural-chessboard/neural-chessboard/laps.py", line 27, in laps_cluster
    Y = scipy.spatial.distance.pdist(points)
  File "/usr/lib/python3.7/site-packages/scipy/spatial/distance.py", line 1872, in pdist
    raise ValueError('A 2-dimensional array must be passed.')
ValueError: A 2-dimensional array must be passed.

**Comment by maciejczyzewski** [comment]
Set in file _config.py_  `NC_DEBUG = True`.
https://github.com/maciejczyzewski/neural-chessboard/blob/draft/config.py#L6
It should provide more information & extra files for visual debugging in `test/steps/`.
**Edit:** run `$ python3 main.py test` to check if everything is working properly.
