### ISSUE TITLE
Not Enough Values to Unpack

### ISSUE THREAD

**Issue by JustinCorilla** [maciejczyzewski/neural-chessboard#5]
i tried to run the main.py after running dataset and train.py but i still got this error
'stty' is not recognized as an internal or external command,
operable program or batch file.

**Comment by WolfgangFahl** [comment]
same here

```
python3 main.py test
<<<  neural-chessboard  >>>
Using TensorFlow backend.
2019-11-09 12:29:26.356840: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-11-09 12:29:26.377845: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fcd3d771180 executing computations on platform Host. Devices:
2019-11-09 12:29:26.377866: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
=================================================================================
[1] LAYER =======================================================================
================================================================================= 

 SLID  (   0.323)s --- 1 step ---------------------------------------------------
--> @pSLID(img)
FILTER: 1 [3, (2, 6), 5] : 40
FILTER: 2 [3, (6, 2), 5] : 28
FILTER: 3 [5, (3, 3), 5] : 39
FILTER: 4 [0, (0, 0), 0] : 29
--> @SLID(img, segments)
--> @slid_tendency(raw_lines)
 LAPS  (   0.491)s --- 2 step ---------------------------------------------------
--> @LAPS(img, lines)
Traceback (most recent call last):
  File "main.py", line 108, in <module>
    modes[mode](args); print(utils.clock(), "done")
  File "main.py", line 80, in test
    detect(args)
  File "main.py", line 63, in detect
    NC_LAYER += 1; layer()
  File "main.py", line 33, in layer
    points = LAPS(NC_IMAGE['main'], lines)
  File "/Users/wf/source/python/neural-chessboard/laps.py", line 111, in LAPS
    re_laps = laps_detector(dimg)
  File "/Users/wf/source/python/neural-chessboard/laps.py", line 59, in laps_detector
    cv2.CHAIN_APPROX_NONE)
ValueError: not enough values to unpack (expected 3, got 2)
```

**Comment by WolfgangFahl** [comment]
see https://stackoverflow.com/questions/54164630/want-to-find-contours-valueerror-not-enough-values-to-unpack-expected-3-go and https://stackoverflow.com/a/55806272/1497139

**Comment by xhtp2000** [comment]
I still have this issue, where should I correct the cv2 function? It seems like os.popen cannot get the Linux console window width in Python.

![stty](https://user-images.githubusercontent.com/17955548/87243014-721af680-c432-11ea-916a-1925c29450d6.JPG)

**Comment by greczimarton** [comment]
@xhtp2000 I had the same issue, stty is a command in macOS or Linux. When I tried running the program on Windows I ran into the same problem. I tried running it on Linux, and it works. (Well its not, but at least its a different problem :D)

**Comment by OmerBaddour** [comment]
I had this same problem, and fixed it by changing line 58 in `laps.py` from:
```
_1, contours, _2  = cv2.findContours(...)
```

to:
```
contours, _2 = cv2.findContours(...)
```
