### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by kevinkengne** [maciejczyzewski/neural-chessboard#7]
I can run dataset.py and train.py fine, however whenever I run main.py I get the following error message:
Traceback (most recent call last):
  File "main.py", line 108, in <module>
    modes[mode](args); print(utils.clock(), "done")
  File "main.py", line 80, in test
    detect(args)
  File "main.py", line 63, in detect
    NC_LAYER += 1; layer()
  File "main.py", line 33, in layer
    points = LAPS(NC_IMAGE['main'], lines)
  File "/Users/kevin/Documents/NeuralChessBoard/neural-chessboard/laps.py", line 111, in LAPS
    re_laps = laps_detector(dimg)
  File "/Users/kevin/Documents/NeuralChessBoard/neural-chessboard/laps.py", line 59, in laps_detector
    cv2.CHAIN_APPROX_NONE)
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by arikanev** [comment]
how did you resolve this?
